### ISSUE TITLE
Fix CLI Design Bugs

### ISSUE THREAD

**Issue by Verssae** [Verssae/toclo#3]
현재 console에서 표가 매끄럽게 출력되지 않는 버그가 있음.
특수문자의 문제로 보임.

- [x] Mac

- [ ] Windows

**Comment by PrismSpirit** [comment]
MacOS에서 정상적으로 작동함을 확인했습니다

**Comment by Verssae** [comment]
@PrismSpirit 일단은 Linux 배포판 이니까 윈도우의 디자인에 관해선 차후에 생각합시다.
