### ISSUE TITLE
todo 테이블을 생성하지 않고 add 나 modify 명령어 입력 시 오류 발생

### ISSUE THREAD

**Issue by PrismSpirit** [Verssae/toclo#9]
todo 테이블을 생성하지 않고 add 나 modify 명령어를 입력 시 오류가 발생합니다

따라서 add 나 modify 명령어 입력 시 todo 테이블이 있는지 확인하고, 없을 시 경고 메세지를 출력합니다

**Comment by Verssae** [comment]
ls 명령에서도 경고를 출력하도록 했습니다.
